/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as FollowUpsRouteImport } from './routes/follow-ups'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as OportunidadesRouteImport } from './routes/oportunidades'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as ProspeccaoRouteImport } from './routes/prospeccao'
import { Route as RapidoRouteImport } from './routes/rapido'
import { Route as TrabalharLeadsRouteImport } from './routes/trabalhar-leads'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpsRoute = FollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const OportunidadesRoute = OportunidadesRouteImport.update({
  id: '/oportunidades',
  path: '/oportunidades',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspeccaoRoute = ProspeccaoRouteImport.update({
  id: '/prospeccao',
  path: '/prospeccao',
  getParentRoute: () => rootRouteImport,
} as any)
const RapidoRoute = RapidoRouteImport.update({
  id: '/rapido',
  path: '/rapido',
  getParentRoute: () => rootRouteImport,
} as any)
const TrabalharLeadsRoute = TrabalharLeadsRouteImport.update({
  id: '/trabalhar-leads',
  path: '/trabalhar-leads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/follow-ups': typeof FollowUpsRoute
  '/leads': typeof LeadsRoute
  '/oportunidades': typeof OportunidadesRoute
  '/pipeline': typeof PipelineRoute
  '/prospeccao': typeof ProspeccaoRoute
  '/rapido': typeof RapidoRoute
  '/trabalhar-leads': typeof TrabalharLeadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/follow-ups': typeof FollowUpsRoute
  '/leads': typeof LeadsRoute
  '/oportunidades': typeof OportunidadesRoute
  '/pipeline': typeof PipelineRoute
  '/prospeccao': typeof ProspeccaoRoute
  '/rapido': typeof RapidoRoute
  '/trabalhar-leads': typeof TrabalharLeadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/follow-ups': typeof FollowUpsRoute
  '/leads': typeof LeadsRoute
  '/oportunidades': typeof OportunidadesRoute
  '/pipeline': typeof PipelineRoute
  '/prospeccao': typeof ProspeccaoRoute
  '/rapido': typeof RapidoRoute
  '/trabalhar-leads': typeof TrabalharLeadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/follow-ups'
    | '/leads'
    | '/oportunidades'
    | '/pipeline'
    | '/prospeccao'
    | '/rapido'
    | '/trabalhar-leads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/follow-ups'
    | '/leads'
    | '/oportunidades'
    | '/pipeline'
    | '/prospeccao'
    | '/rapido'
    | '/trabalhar-leads'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/follow-ups'
    | '/leads'
    | '/oportunidades'
    | '/pipeline'
    | '/prospeccao'
    | '/rapido'
    | '/trabalhar-leads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  FollowUpsRoute: typeof FollowUpsRoute
  LeadsRoute: typeof LeadsRoute
  OportunidadesRoute: typeof OportunidadesRoute
  PipelineRoute: typeof PipelineRoute
  ProspeccaoRoute: typeof ProspeccaoRoute
  RapidoRoute: typeof RapidoRoute
  TrabalharLeadsRoute: typeof TrabalharLeadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-ups': {
      id: '/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof FollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oportunidades': {
      id: '/oportunidades'
      path: '/oportunidades'
      fullPath: '/oportunidades'
      preLoaderRoute: typeof OportunidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospeccao': {
      id: '/prospeccao'
      path: '/prospeccao'
      fullPath: '/prospeccao'
      preLoaderRoute: typeof ProspeccaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapido': {
      id: '/rapido'
      path: '/rapido'
      fullPath: '/rapido'
      preLoaderRoute: typeof RapidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trabalhar-leads': {
      id: '/trabalhar-leads'
      path: '/trabalhar-leads'
      fullPath: '/trabalhar-leads'
      preLoaderRoute: typeof TrabalharLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FollowUpsRoute: FollowUpsRoute,
  LeadsRoute: LeadsRoute,
  OportunidadesRoute: OportunidadesRoute,
  PipelineRoute: PipelineRoute,
  ProspeccaoRoute: ProspeccaoRoute,
  RapidoRoute: RapidoRoute,
  TrabalharLeadsRoute: TrabalharLeadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
